# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02d39931e91e4338f24e7579219371a91ceadbf88370d978294159e1df3ecbe5e6fd268cdc709484e55016661dc773afef59c05c58581d5bbc95379bf49a81d0

test:
  secret_key_base: 37728d0767b0b1a09e80f1d406d2f05f6835a1d127ada328182284719e884e695728cc24f927322c0becc26735976e19157a1317a63ad12ab8b9b4fccf6714c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
